from __future__ import annotations

import json
from pathlib import Path

from .manifest import Dialogue, VoiceCue


DISCLOSURE = (
    "Fictional AI-generated parody performance for a video-game mod; "
    "not an authentic recording or statement."
)


def estimate_script(
    entries: list[Dialogue],
    words_per_minute: int = 150,
    cues: list[VoiceCue] | None = None,
) -> dict[str, float | int]:
    words = sum(
        len(line.split())
        for entry in entries
        for page in entry.pages
        for line in page.lines
    )
    words += sum(len(cue.text.split()) for cue in cues or [])
    seconds = words * 60.0 / words_per_minute
    pcm_bytes = int(seconds * 16000 * 2)
    vadpcm_bytes = int(seconds * 16000 * 9 / 16)
    return {
        "pages": sum(len(entry.pages) for entry in entries),
        "cues": len(cues or []),
        "words": words,
        "words_per_minute": words_per_minute,
        "seconds": seconds,
        "pcm_bytes": pcm_bytes,
        "vadpcm_bytes": vadpcm_bytes,
    }


def export_voice_script(
    entries: list[Dialogue], output: Path, cues: list[VoiceCue] | None = None
) -> None:
    clips = []
    for entry in sorted(entries, key=lambda item: item.message_id):
        for page_index, page in enumerate(entry.pages):
            clips.append(
                {
                    "file": page.voice,
                    "message_id": f"0x{entry.message_id:04X}",
                    "page_index": page_index,
                    "context": entry.context,
                    "required_hint": entry.required_hint,
                    "text": " ".join(page.lines),
                    "direction": (
                        "Clearly fictional, boastful political-parody caricature; "
                        "energetic but intelligible; no added words."
                    ),
                }
            )
    for cue in cues or []:
        clips.append(
            {
                "file": cue.voice,
                "cue": cue.name,
                "context": cue.context,
                "text": cue.text,
                "replaces": list(cue.replaces),
                "direction": (
                    "Clearly fictional, boastful political-parody caricature; "
                    "short, energetic, and intelligible; no added words."
                ),
            }
        )
    payload = {
        "schema_version": 1,
        "disclosure": DISCLOSURE,
        "audio_contract": {
            "format": "WAV",
            "encoding": "signed 16-bit PCM",
            "channels": 1,
            "sample_rate_hz": 16000,
            "maximum_seconds": 8.0,
            "trim_silence": True,
        },
        "clips": clips,
    }
    output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _symbol(entry: Dialogue, page_index: int) -> str:
    return f"NA_SE_VO_TRUMP_{entry.message_id:04X}_{page_index:02d}"


def generate_voice_map(entries: list[Dialogue], output: Path) -> None:
    lines = [
        "/* Generated by `oot-trump prepare-voice`; do not edit. */",
        "typedef struct TrumpVoicePage {",
        "    u16 textId;",
        "    u8 pageIndex;",
        "    u16 sfxId;",
        "} TrumpVoicePage;",
        "",
        "static TrumpVoicePage sTrumpVoicePages[] = {",
    ]
    for entry in sorted(entries, key=lambda item: item.message_id):
        for page_index, _page in enumerate(entry.pages):
            lines.append(
                f"    {{ 0x{entry.message_id:04X}, {page_index}, {_symbol(entry, page_index)} }},"
            )
    lines.extend(["};", ""])
    output.write_text("\n".join(lines), encoding="utf-8")
